services:
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: weatherDB
      POSTGRES_PASSWORD: db_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - weather_network

  server:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PASSWORD: db_password
      DB_NAME: weatherDB
      DB_USER: postgres
      WEATHER_API_CODE: api_code
      SECRET_KEY: secret_key
      DEBUG: "True"
    restart: always
    networks:
      - weather_network
    volumes:
      - weather_static:/app/static
      - weather_media:/app/media

  nginx:
    image: nginx:1.25.3-alpine-slim
    volumes:
      - weather_static:/static
      - weather_media:/media
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - weather_network

volumes:
  pg_data:
  weather_static:
  weather_media:

networks:
  weather_network:
    driver: bridge
